### ISSUE TITLE
Adding helm chart for greenlight API

### ISSUE THREAD

**Issue by mahesh-singh** [mahesh-singh/greenlight#1]
**Created a production-ready Helm chart for your Greenlight API with:**

Proper templating and helpers
Configurable values for all aspects
Health checks and probes
Service account creation
Ingress support
Environment variable injection from secrets

**Your Action Items for This Step**

Create the directory structure using the first artifact
Copy the chart files from the second artifact into the appropriate locations
Test the chart using the commands in the third artifact
Compare with your existing manifest and adjust values as needed

**Key Learning Points**

Helm Templates: Notice how we use {{ }} for templating and {{- }} to trim whitespace
Values Hierarchy: Values can be overridden at install/upgrade time
Helper Functions: _helpers.tpl contains reusable template functions
Labels & Selectors: Following Kubernetes recommended labels

**Comment by mahesh-singh** [comment]
anki:
kubectl get events --sort-by=.metadata.creationTimestamp
kubectl describe pod greenlight-api-5d754d474b-tk4fw

**Comment by mahesh-singh** [comment]
NextSteo
- Setup secret
- Setup DB
Prompt  - https://claude.ai/chat/0fa304e0-6377-4c94-918f-8bbb29f9b6ea

**Comment by mahesh-singh** [comment]
# Kubernetes to Helm Migration - Step 2: PostgreSQL Chart

## Original Problem Statement
I'm migrating a fully working K8s stack from raw YAML manifests to Helm charts. The stack includes:
- REST API (`greenlight-api`) ✅ COMPLETED
- PostgreSQL DB ⏳ NEXT
- Vault 
- Observability stack (Prometheus + Grafana)

**Goal**: Each service should have its own chart, with an umbrella chart to manage everything together.

## Target Directory Structure
```
helm/
├── greenlight-api/          ✅ COMPLETED
├── postgres/               ⏳ WORKING ON THIS
├── vault/
├── observability/
│   ├── prometheus/
│   └── grafana/
└── greenlight-stack/        # umbrella chart
```

## Current Status
- ✅ **Greenlight API chart**: Created and tested successfully
- ✅ **Directory structure**: Set up
- ⏳ **PostgreSQL chart**: Need to create next

## My Current PostgreSQL Manifests
```yaml
# Please include your actual PostgreSQL manifests here, for example:
# - Deployment
# - Service  
# - PVC/StorageClass
# - ConfigMap (if any)
# - Secret (if any)

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: greenlight-api
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      nodeSelector:
        type: database
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-password
        - name: POSTGRES_DB
          value: greenlight
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: greenlight-api
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: greenlight-api
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: greenlight-api
spec:
  template:
    spec:
      nodeSelector:
        type: database
      containers:
      - name: migrate
        image: migrate/migrate
        args:
        - "-path"
        - "/migrations"
        - "-database"
        - "$(DB_DSN)"
        - "up"
        env:
        - name: DB_DSN
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: db-dsn
        volumeMounts:
        - name: migrations
          mountPath: /migrations
      volumes:
      - name: migrations
        configMap:
          name: migrations-configmap
      restartPolicy: OnFailure
```

## Completed Greenlight API Chart Pattern
I've already created the greenlight-api chart with this structure:
- `Chart.yaml` - metadata
- `values.yaml` - configuration
- `templates/_helpers.tpl` - helper functions
- `templates/deployment.yaml` - deployment template
- `templates/service.yaml` - service template
- `templates/serviceaccount.yaml` - service account
- `templates/ingress.yaml` - ingress (optional)

The API chart follows these patterns:
- Templated resource names using helpers
- Configurable via values.yaml
- Environment variables from secrets
- Health checks configured
- Standard Kubernetes labels

## Requirements for PostgreSQL Chart
1. **Follow same patterns** as the API chart
2. **Configurable**: database name, user, password, storage size
3. **Persistent storage**: PVC with configurable storage class
4. **Security**: Use secrets for sensitive data (for now we can hard code the secret, and in next step we can use that)
5. **Integration**: Should work with the API chart (database connection)
6. **Environment flexibility**: dev/staging/prod configurations

## Integration Notes
- The API chart expects a secret called `greenlight-secrets` with key `database-url`
- PostgreSQL chart should create this secret or be compatible with it
- Consider how the charts will work together in the umbrella chart

## Questions to Address
1. Should PostgreSQL chart create the database secret that API needs?
2. How to handle database initialization/migrations?
3. What storage class and size defaults to use?
4. Should we vendor a community chart (like Bitnami) or create from scratch?

Please help me create the PostgreSQL Helm chart that integrates well with my existing API chart and follows the same best practices.
